name: bookstack
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - APP_URL=https://hytech.benhall.tech
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=deleteme
      - DB_PASS=deleteme
      - DB_DATABASE=bookstackapp
    volumes:
      - /replaceme:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db

  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - MYSQL_ROOT_PASSWORD=deleteme
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=deleteme
      - MYSQL_PASSWORD=deleteme
    volumes:
      - /replaceme:/config
    restart: unless-stopped