name: lazylibrarian
services:
  lazylibrarian:
    image: lscr.io/linuxserver/lazylibrarian:latest
    container_name: lazylibrarian
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre|linuxserver/mods:lazylibrarian-ffmpeg #optional
    volumes:
      - /mnt/data/lazylibrarian/data:/config
      - /mnt/data/ll_downloads/:/downloads
      - /mnt/data/ll_books/:/books #optional
    ports:
      - 5299:5299
    restart: unless-stopped