# Auto-generated using compose2nix v0.3.1.
{ config, pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."bookstack" = {
    image = "lscr.io/linuxserver/bookstack";
    environment = {
      "APP_URL" = "https://wiki.yeet";
      "DB_DATABASE" = "bookstackapp";
      "DB_HOST" = "bookstack_db";
      "DB_PORT" = "3306";
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "America/New_York";
    };
    
    # "DB_USER" = "deleteme";
    # "DB_PASS" = "deleteme";
    environmentFiles = [ config.age.secrets.nebs-bookstack-env-file.path ];
    volumes = [
      "/mnt/data/bookstack_data:/config:rw"
    ];
    ports = [
      "6875:80/tcp"
    ];
    dependsOn = [
      "bookstack_db"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=bookstack"
      "--network=bookstack_default"
    ];
  };
  systemd.services."docker-bookstack" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-bookstack_default.service"
    ];
    requires = [
      "docker-network-bookstack_default.service"
    ];
    partOf = [
      "docker-compose-bookstack-root.target"
    ];
    wantedBy = [
      "docker-compose-bookstack-root.target"
    ];
  };
  virtualisation.oci-containers.containers."bookstack_db" = {
    image = "lscr.io/linuxserver/mariadb";
    environment = {
      "MYSQL_DATABASE" = "bookstackapp";
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "America/New_York";
    };
    # "MYSQL_ROOT_PASSWORD" = "deleteme";
    # "MYSQL_USER" = "deleteme";
    # "MYSQL_PASSWORD" = "deleteme";
    environmentFiles = [ config.age.secrets.nebs-bookstack-env-file.path ];
    volumes = [
      "/mnt/data/bookstack_db:/config:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=bookstack_db"
      "--network=bookstack_default"
    ];
  };
  systemd.services."docker-bookstack_db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-bookstack_default.service"
    ];
    requires = [
      "docker-network-bookstack_default.service"
    ];
    partOf = [
      "docker-compose-bookstack-root.target"
    ];
    wantedBy = [
      "docker-compose-bookstack-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-bookstack_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f bookstack_default";
    };
    script = ''
      docker network inspect bookstack_default || docker network create bookstack_default
    '';
    partOf = [ "docker-compose-bookstack-root.target" ];
    wantedBy = [ "docker-compose-bookstack-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-bookstack-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
